name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      src-changed: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - doc/*

  build-and-commit:
    needs: check-changes
    permissions:
      contents: write
    if: ${{ needs.check-changes.outputs.src-changed == 'true' }}
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: public
      - name: Build AsciiDoc
        run: |
          asciidoctor -D public/${{ github.ref_name }} doc/rvariant.adoc
          cd public
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git add .
          git commit -m "Update rvariant.html"
          git push
