name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: doc/

  # deploy-for-PR:
  #   needs: upload
  #   if: github.event_name == 'pull_request'

  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages-${{ github.event.pull_request.id }}
  #     url: ${{ steps.deployment.outputs.page_url }}${{ github.event.pull_request.id }}/rvariant.html

  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/deploy-pages@v4
  #       id: deployment

  deploy:
    needs: upload
    # if: github.event_name == 'push'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}rvariant.html

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
