name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - doc/*

  build:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build AsciiDoc
        run: |
          apk update && apk add tar
          asciidoctor -D public/${{ github.ref_name }} doc/rvariant.adoc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ github.ref_name }}/rvariant.html

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
