name: Deploy

on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p public/${{ github.ref_name }}
          cp -r doc/* public/${{ github.ref_name }}/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: upload

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ github.ref_name }}/rvariant.html

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
