name: Deploy

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://asciidoctor/docker-asciidoctor:latest
      - run: |
          asciidoctor -D public/${{ github.ref_name }} rvariant.adoc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: upload

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ github.ref_name }}/rvariant.html

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
